// Generated by telemetry/tools/gen_catalog.py from fabric/telemetry.toml. Do not edit.
// Storage-free handles for every build level, including off (RFC-0001 §5, RFC-0002 §1).
#pragma once

#include <ostia/telemetry/handles.hpp>

namespace ostia::fabric::catalog {

// ostia.fabric.bytes_sent (counter, unit By, dimensions: transport): Bytes handed to a transport
// for sending.
inline constexpr ::ostia::telemetry::MetricHandle bytes_sent{
    0, ::ostia::telemetry::MetricKind::counter};
// ostia.fabric.progress_loop_latency (histogram, unit ns)
inline constexpr ::ostia::telemetry::MetricHandle progress_loop_latency{
    1, ::ostia::telemetry::MetricKind::histogram};
// fabric.chunk_send (arg0=bytes, arg1=chunk)
inline constexpr ::ostia::telemetry::EventHandle chunk_send{0};

} // namespace ostia::fabric::catalog
