#!/usr/bin/env python3
"""Turn a component's telemetry catalog into storage-free handles (RFC-0002 §1).

    gen_catalog.py --component fabric --catalog fabric/telemetry.toml --out <header>

The catalog uses RFC-0002 §1's schema: [[metric]] (name, kind, unit, description,
dimensions), [[attribute]] (name, values or max_cardinality) and [[event]] (name, args).
The generated header holds one `constexpr` handle per metric and event, in every build
level including `off`, so instrumentation call sites always compile (RFC-0001 §5). The
handles carry no storage. Counter storage, export and the full validation of RFC-0002
(memory budget, UCUM units, mirrored metrics) arrive with its implementation (PR 8).
"""

import argparse
import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

KINDS = ("counter", "updown", "histogram", "gauge")
SNAKE = re.compile(r"^[a-z][a-z0-9_]*$")


class CatalogError(ValueError):
    pass


@dataclass
class Metric:
    name: str
    handle: str
    kind: str
    unit: str
    description: str
    dimensions: list[str] = field(default_factory=list)


@dataclass
class Event:
    name: str
    handle: str
    args: dict[str, str] = field(default_factory=dict)


@dataclass
class Catalog:
    metrics: list[Metric]
    events: list[Event]


def _handle(name: str, prefix: str, what: str) -> str:
    if not name.startswith(prefix):
        raise CatalogError(f"{what} '{name}' must start with {prefix}")
    handle = name[len(prefix) :]
    if not SNAKE.match(handle):
        raise CatalogError(f"{what} '{name}': the part after {prefix} must be lower_snake_case")
    return handle


def load(path: Path, component: str) -> Catalog:
    data = tomllib.loads(path.read_text())
    attributes = {a["name"] for a in data.get("attribute", [])}
    metrics: list[Metric] = []
    seen: set[str] = set()
    for m in data.get("metric", []):
        name = m.get("name", "")
        handle = _handle(name, f"ostia.{component}.", "metric")
        if name in seen:
            raise CatalogError(f"metric '{name}' is declared twice")
        seen.add(name)
        if m.get("kind") not in KINDS:
            raise CatalogError(f"metric '{name}': kind must be one of {', '.join(KINDS)}")
        if not m.get("unit"):
            raise CatalogError(f"metric '{name}' needs a unit (UCUM, e.g. By, ns, 1)")
        for d in m.get("dimensions", []):
            if d not in attributes:
                raise CatalogError(f"metric '{name}' uses undeclared attribute '{d}'")
        metrics.append(
            Metric(
                name,
                handle,
                m["kind"],
                m["unit"],
                m.get("description", ""),
                m.get("dimensions", []),
            )
        )
    events: list[Event] = []
    for i, e in enumerate(data.get("event", [])):
        name = e.get("name", "")
        handle = _handle(name, f"{component}.", "event")
        if name in seen:
            raise CatalogError(f"event '{name}' is declared twice")
        seen.add(name)
        events.append(Event(name, handle, dict(e.get("args", {}))))
    return Catalog(metrics, events)


def render(component: str, catalog: Catalog, source: str) -> str:
    lines = [
        f"// Generated by telemetry/tools/gen_catalog.py from {source}. Do not edit.",
        "// Storage-free handles for every build level, including off (RFC-0001 §5, RFC-0002 §1).",
        "#pragma once",
        "",
        "#include <ostia/telemetry/handles.hpp>",
        "",
        f"namespace ostia::{component}::catalog {{",
        "",
    ]
    for i, m in enumerate(catalog.metrics):
        dims = f", dimensions: {', '.join(m.dimensions)}" if m.dimensions else ""
        lines.append(
            f"// {m.name} ({m.kind}, unit {m.unit}{dims}){': ' if m.description else ''}{m.description}"
        )
        lines.append(
            f"inline constexpr ::ostia::telemetry::MetricHandle {m.handle}{{{i}, "
            f"::ostia::telemetry::MetricKind::{m.kind}}};"
        )
    for i, e in enumerate(catalog.events):
        args = ", ".join(f"{k}={v}" for k, v in e.args.items())
        lines.append(f"// {e.name}{' (' + args + ')' if args else ''}")
        lines.append(f"inline constexpr ::ostia::telemetry::EventHandle {e.handle}{{{i}}};")
    lines += ["", f"}} // namespace ostia::{component}::catalog", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--component", required=True)
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--source", help="catalog path shown in the header (default: --catalog)")
    args = parser.parse_args(argv)
    try:
        catalog = load(args.catalog, args.component)
    except (CatalogError, tomllib.TOMLDecodeError, KeyError) as e:
        print(
            f"error: {args.catalog}: {e}\n"
            "  rule: telemetry catalogs follow RFC-0002 §1's schema\n"
            f"  fix: correct the entry in {args.catalog}\n"
            "  see: RFC-0002 §1",
            file=sys.stderr,
        )
        return 1
    text = render(args.component, catalog, args.source or str(args.catalog))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    if not args.out.exists() or args.out.read_text() != text:
        args.out.write_text(text)  # unchanged output keeps its timestamp: no rebuild
    return 0


if __name__ == "__main__":
    sys.exit(main())
