#!/usr/bin/env python3
"""setsid stand-in for hosts without util-linux (macOS): `setsid [-w] prog args...`."""

import os
import sys

args = sys.argv[1:]
if args and args[0] in ("-w", "--wait"):
    args = args[1:]
try:
    os.setsid()
except PermissionError:  # already a process group leader: fork, as util-linux does
    pid = os.fork()
    if pid:
        _, status = os.waitpid(pid, 0)
        sys.exit(os.waitstatus_to_exitcode(status))
    os.setsid()
os.execvp(args[0], args)
